### ISSUE TITLE
エラーについて

### ISSUE THREAD

**Issue by mayo233** [TIERS/tello-ros2-gazebo#1]
ros2のdashingでtello_gazeboパッケージ内のsimple_launch.pyを実行しようとした所、下記のようなエラーが出ました

```
 suzukamayo@suzukamayo-N850EP6:~/tello_ros_ws$ ros2 launch tello_gazebo simple_launch.py
 Package 'tello_gazebo' not found: "package 'tello_gazebo' not found, searching: ['/home/suzukamayo/tello_ros_ws/install/tello_msgs', '/home/suzukamayo/tello_ros_ws/install/tello_description', '/home/suzukamayo/tello_ros_ws/install/ros2_shared', '/opt/ros/dashing']"
```

どうすればパッケージの実行が出来ますか？

**Comment by jopequ** [comment]
Hi, this is a late answer but for other people looking, it seems you did not source the `install/setup.bash` file after building the package in your workspace. In any case we have not tried this on Dashing.
