### ISSUE TITLE
Can't control drone on CLI.

### ISSUE THREAD

**Issue by elyancorrea** [TIERS/tello-ros2-gazebo#3]
When I run:

`cd ~/tello_ros_ws
source install/setup.bash
export GAZEBO_MODEL_PATH=${PWD}/install/tello_gazebo/share/tello_gazebo/models
source /usr/share/gazebo/setup.sh
ros2 launch tello_gazebo simple_launch.py`

Gazebo starts and shows 1 drone.

If I type on CLI:

`ros2 service call /drone1/tello_action tello_msgs/TelloAction "{cmd: 'takeoff'}"`

I get this response:

`The passed service type is invalid`

If  I run

`ros2 service list`

I get:

`/camera_controller_1/describe_parameters
/camera_controller_1/get_parameter_types
/camera_controller_1/get_parameters
/camera_controller_1/list_parameters
/camera_controller_1/set_parameters
/camera_controller_1/set_parameters_atomically
/delete_entity
/drone1/TelloPlugin/describe_parameters
/drone1/TelloPlugin/get_parameter_types
/drone1/TelloPlugin/get_parameters
/drone1/TelloPlugin/list_parameters
/drone1/TelloPlugin/set_parameters
/drone1/TelloPlugin/set_parameters_atomically
/drone1/ground_truth/describe_parameters
/drone1/ground_truth/get_parameter_types
/drone1/ground_truth/get_parameters
/drone1/ground_truth/list_parameters
/drone1/ground_truth/set_parameters
/drone1/ground_truth/set_parameters_atomically
/drone1/joy_node/describe_parameters
/drone1/joy_node/get_parameter_types
/drone1/joy_node/get_parameters
/drone1/joy_node/list_parameters
/drone1/joy_node/set_parameters
/drone1/joy_node/set_parameters_atomically
/drone1/tello_action
/drone1/tello_joy/describe_parameters
/drone1/tello_joy/get_parameter_types
/drone1/tello_joy/get_parameters
/drone1/tello_joy/list_parameters
/drone1/tello_joy/set_parameters
/drone1/tello_joy/set_parameters_atomically
/gazebo/describe_parameters
/gazebo/get_parameter_types
/gazebo/get_parameters
/gazebo/list_parameters
/gazebo/set_parameters
/gazebo/set_parameters_atomically
/get_model_list
/pause_physics
/reset_simulation
/reset_world
/robot_state_publisher/describe_parameters
/robot_state_publisher/get_parameter_types
/robot_state_publisher/get_parameters
/robot_state_publisher/list_parameters
/robot_state_publisher/set_parameters
/robot_state_publisher/set_parameters_atomically
/set_camera_info
/spawn_entity
/unpause_physics`

I can't control drone without a joystick?

**Comment by jopequ** [comment]
Hi @elyancorrea, sorry for the late reply, I am guessing you probably forgot to run `source install/setup.bash` in the second terminal where you call the service?
