### ISSUE TITLE
Do we have this model to run in ros 1 (noetic)? 

### ISSUE THREAD

**Issue by Gfernandes10** [TIERS/tello-ros2-gazebo#4]
Would it be possible to run in ros 1 (noetic)? 

Do you have any other package of the Tello model in gazebo that could be ran in noetic? 

Thanks!

**Comment by jopequ** [comment]
Hi @Gfernandes10 , we have only been using these with ROS 2. 
However, you can test an alternative drone simulator for ROS Noetic:

https://github.com/TIERS/drone-racing

Together with a ROS 1 driver for the actual Tello drone:

https://github.com/TIERS/tello-driver-ros

I hope this helps!
