### ISSUE TITLE
Error while running Colcon Build

### ISSUE THREAD

**Issue by mich1342** [TIERS/tello-ros2-gazebo#5]
Hi, I am trying to build this package using ROS2 Humble in Ubuntu 22.04. I got Permission Denied on the tello_description package on the /src/replace.py.

**Comment by sbarcelona11** [comment]
Can you try this command  before compiling `sudo chmod +x tello-ros2-gazebo/tello_ros/tello_description/src/replace.py
`

**Comment by szation** [comment]
@sbarcelona11 
I had the same problem and the permission issue has been resolved with your answer.
I also had to modify `tello-ros2-gazebo/tello_ros/tello_driver/CMakeLists.txt` file, according to the following commit;
https://github.com/clydemcqueen/tello_ros/commit/c2b7b47d681513f0fc368d68b700910536d7b97c

And it works fine in Humble,
Thanks!

**Comment by mich1342** [comment]
Hi @sbarcelona11  & @szation,

Thanks for your help, it is working well not following both of your recommendations
